# Generated by Django 4.1.1 on 2022-09-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=15, null=True)),
                ('name_ru', models.CharField(max_length=60)),
                ('name_en', models.CharField(max_length=60)),
                ('coordinates', models.CharField(max_length=155)),
                ('timezone', models.CharField(max_length=85)),
                ('parent_name_en', models.CharField(max_length=75)),
            ],
        ),
    ]
