# Generated by Django 4.1.1 on 2022-09-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airports',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='airports',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='airports',
            name='type',
        ),
    ]
