# Generated by Django 4.1.3 on 2022-12-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyapp', '0002_remove_airports_coordinates_remove_airports_timezone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=5, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('continent', models.CharField(max_length=10, null=True)),
                ('municipality', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
