# Generated by Django 4.1.3 on 2022-12-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyapp', '0003_airport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airports',
        ),
    ]
