# Generated by Django 4.1.3 on 2022-12-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyapp', '0004_delete_airports'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='city_code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
